# -*- coding: utf-8 -*-
"""untung jawa mangrove.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHIc85GPBg2xOdt1heFfJ-LMZeEp_1Od
"""

# train_mangrove_model.py

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib

# Load data
df = pd.read_csv('dummy_mangrove_dataset.csv')

# Preprocessing
X = df[['Tinggi (cm)', 'Jumlah Daun', 'Diameter Batang (cm)', 'Jumlah Akar Udara', 'Tahun Penanaman']]
y = df['Kondisi Pertumbuhan']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Save the model
joblib.dump(model, 'mangrove_growth_model.pkl')

print("Model saved successfully as mangrove_growth_model.pkl")